FROM hudl/eurus-base:latest
MAINTAINER Joan Alabort <joan.alabort@hudl.com>

RUN ln /dev/null /dev/raw1394
RUN mkdir -p /root/.pip/ && printf "[global]\nindex-url = http://pypi.hudltools.com\ntrusted-host = pypi.hudltools.com\n" >> /root/.pip/pip.conf

WORKDIR /eurus
RUN pip install https://s3.amazonaws.com/pytorch/whl/cu75/torch-0.1.9.post2-cp36-cp36m-linux_x86_64.whl
COPY requirements.txt .
RUN pip install -r requirements.txt

COPY eurus eurus
COPY setup.py .
RUN pip install -e .

WORKDIR /eurus/eurus

EXPOSE 8000
ENTRYPOINT ["gunicorn", "server:app"]