FROM hudl/eurus-base:latest
MAINTAINER Joan Alabort <joan.alabort@hudl.com>

RUN apt-get update -y && apt-get install python-qt4 -y
RUN mkdir -p /root/.config/matplotlib && echo "backend: agg\n" > /root/.config/matplotlib/matplotlibrc

RUN pip install jupyter==1.0.0 ipywidgets==6.0.0 ipython-genutils==0.2.0
RUN mkdir ~/.jupyter
COPY docker/jupyter_notebook_config.py /root/.jupyter/jupyter_notebook_config.py
RUN jupyter nbextension enable --py --sys-prefix widgetsnbextension

WORKDIR /

EXPOSE 8888 22 6006
ENTRYPOINT ["/bin/sh", "-c", "jupyter notebook --no-browser --ip '*' --log-level 'DEBUG'"]
