FROM hudl/eurus-base:latest
MAINTAINER Joan Alabort <joan.alabort@hudl.com>

RUN apt-get update -y && apt-get install python-qt4 -y
RUN mkdir -p /root/.config/matplotlib && echo "backend: agg\n" > /root/.config/matplotlib/matplotlibrc

RUN mkdir -p /root/.pip/ && printf "[global]\nindex-url = http://pypi.hudltools.com\ntrusted-host = pypi.hudltools.com\n" >> /root/.pip/pip.conf

RUN pip install jupyter==1.0.0
RUN jupyter nbextension enable --py --sys-prefix widgetsnbextension

WORKDIR /

EXPOSE 8888 22 6006
ENTRYPOINT ["/bin/sh", "-c", "jupyter notebook --no-browser --ip '*' --log-level 'DEBUG'"]
