FROM hudl/ffmpeg-gpu
MAINTAINER Joan Alabort <joan.alabort@hudl.com>

RUN wget --quiet https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O install_miniconda.sh && \
    /bin/bash install_miniconda.sh -b -p /opt/conda && \
    rm install_miniconda.sh
ENV PATH /opt/conda/bin:$PATH
RUN conda install numpy==1.12.0 -y

WORKDIR /
RUN git clone https://github.com/Itseez/opencv.git
WORKDIR /opencv
#RUN git checkout tags/3.2.0

WORKDIR /
RUN git clone https://github.com/Itseez/opencv_contrib.git
WORKDIR /opencv_contrib
#RUN git checkout tags/3.2.0

WORKDIR /opencv
RUN cmake -D CMAKE_BUILD_TYPE=Release \
    -D CMAKE_INSTALL_PREFIX=/opt/opencv \
    -D OPENCV_EXTRA_MODULES_PATH=../opencv_contrib/modules \
    -D OPENCV_ENABLE_NONFREE=False \
    -D BUILD_SHARED_LIBS=True \
    -D BUILD_opencv_python3=True \
    -D OPENCV_FORCE_PYTHON_LIBS=True \
    -D PYTHON_INCLUDE_DIR=/opt/conda/include/python3.6m \
    -D PYTHON_LIBRARY=/opt/conda/lib/libpython3.6m.so \
    -D PYTHON3_INCLUDE_DIR=/opt/conda/include/python3.6m \
    -D PYTHON3_LIBRARY=/opt/conda/lib/libpython3.6m.so \
    -D PYTHON3_EXECUTABLE=/opt/conda/bin/python3.6 \
    -D PYTHON3_NUMPY_INCLUDE_DIRS=/opt/conda/pkgs/numpy-1.12.0-py36_0/lib/python3.6/site-packages/numpy/core/include \
    -D PYTHON3_PACKAGES_PATH=/opt/conda/lib/python3.6/site-packages \
    -D BUILD_EXAMPLES=False \
    -D INSTALL_PYTHON_EXAMPLES=False \
    -D INSTALL_C_EXAMPLES=False \
    -D BUILD_DOCS=False \
    -D BUILD_TESTS=False \
    -D BUILD_PERF_TESTS=False \
    -D WITH_CUDA=False \
    .

RUN make -j 8 && make install && \
    ldconfig && \
    cd .. && \
    rm -rf opencv && \
    rm -rf opencv_contrib

RUN ln /dev/null /dev/raw1394

RUN conda install -c soumith pytorch torchvision cuda80 -y

RUN mkdir -p /root/.pip/ && printf "[global]\nindex-url = http://pypi.hudltools.com\ntrusted-host = pypi.hudltools.com\n" >> /root/.pip/pip.conf

ENTRYPOINT ["/bin/bash"]
