FROM hudl/eurus-base:latest
MAINTAINER Joan Alabort <joan.alabort@hudl.com>

WORKDIR /eurus
COPY requirements.txt .
RUN pip install -r requirements.txt

COPY eurus eurus
COPY setup.py .
RUN pip install -e .

WORKDIR /eurus/eurus

EXPOSE 8000
ENTRYPOINT ["gunicorn", "server:app"]
