FROM hudl/opencv:latest
MAINTAINER Joan Alabort <joan.alabort@hudl.com>

RUN apt-get update -y && apt-get install python-qt4 -y
RUN mkdir -p /root/.config/matplotlib && echo "backend: agg\n" > /root/.config/matplotlib/matplotlibrc

RUN mkdir -p /root/.pip/ && printf "[global]\nindex-url = http://pypi.hudltools.com\ntrusted-host = pypi.hudltools.com\n" >> /root/.pip/pip.conf

WORKDIR /eurus
RUN pip install https://s3.amazonaws.com/pytorch/whl/cu75/torch-0.1.9.post2-cp36-cp36m-linux_x86_64.whl
COPY requirements.txt .
RUN pip install -r requirements.txt

COPY eurus eurus
COPY setup.py .
RUN pip install -e .

WORKDIR /eurus/eurus
